name: release

on:
  push:
    tags:
      # matches things like v0.1.6+1.18.2
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+.[0-9]+.[0-9]+'
      # matches things like v0.2.0+1.19
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag Version
        uses: dawidd6/action-get-tag@v1
        id: tag_version
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
        env:
          RELEASE_TAG: ${{ steps.tag_version.outputs.tag }}
      - name: curseforge and modrinth release
        run: ./gradlew curseforge modrinth modrinthSyncBody
        env:
          RELEASE_TAG: ${{ steps.tag_version.outputs.tag }}
          CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
      - name: github release
        uses: softprops/action-gh-release@59c3b4891632ff9a897f99a91d7bc557467a3a22
        with:
          body_path: changelogs/changelog-${{ steps.tag_version.outputs.tag }}.md
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This is the mess that publishes discord notifications
      - name: Read Changelog File
        uses: juliangruber/read-file-action@v1
        id: changelog
        with:
          path: changelogs/changelog-${{ steps.tag_version.outputs.tag }}.md
      - name: Process Changelog for Announcement
        uses: actions/github-script@v6
        id: announcement_text
        env:
          CHANGELOG: ${{ steps.changelog.outputs.content }}
          TAG_VERSION: ${{ steps.tag_version.outputs.tag }}
        with:
          script: |
            let fullVersion = process.env.TAG_VERSION;
            let versions = fullVersion.split('+');
            let modVersion = fullVersion.substring(1);
            let lines = process.env.CHANGELOG.split('\n');
            let changesStart = lines.findIndex(line => line.startsWith('*'));
            lines.splice(0, changesStart);
            lines.unshift(`**Magical Mahou ${versions[0]} has been released for Minecraft ${versions[1]}!**`, '', '__Changes:__');
            lines.push(`Available on Modrinth: https://modrinth.com/mod/magical-mahou/version/${modVersion}`);
            lines.push('Available on CurseForge: https://www.curseforge.com/minecraft/mc-mods/magical-mahou');
            return lines.join('\n');
          result-encoding: string
      - name: Make Release Announcement
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ${{ steps.announcement_text.outputs.result }}
